import { readFile, unlink } from 'node:fs/promises'
import { join } from 'node:path'
import { connect, disconnect } from '../api/src/db.js'
import { Article } from '../api/src/models/Article.js'
import { Page } from '../api/src/models/Page.js'
import { Image } from '../api/src/models/Image.js'
import { processImage } from '../api/src/lib/imagePipeline.js'
import { PAGE_KEYS, RESERVED_SLUGS } from '../api/src/lib/constants.js'
import { uniqueSlug } from '../api/src/lib/slug.js'

/** WordPress page slugs to our page keys. Unlisted slugs are skipped (with a warning). */
const PAGE_KEY_BY_SLUG = {
  accueil: 'home', home: 'home',
  oeuvres: 'works', works: 'works',
  biographie: 'biography', biography: 'biography',
  contact: 'contact',
  bibliographie: 'bibliography', bibliography: 'bibliography',
  liens: 'links', links: 'links',
  'mentions-legales': 'legal', 'terms-and-conditions': 'legal',
}

/**
 * Replaces `{ legacyWpId }` placeholders inside image/gallery blocks with the
 * real Mongo ObjectId, using the map built while importing media. A legacy id
 * that never resolved to an imported image (file missing, or genuinely never
 * imported) means the block is dropped entirely: a missing file must never
 * become a dangling reference in the loaded content.
 */
export function resolveBlockImages(blocks = [], byLegacyId) {
  const out = []
  for (const block of blocks) {
    if (block.type === 'image') {
      const id = byLegacyId.get(block.image?.legacyWpId)
      if (id) out.push({ ...block, image: id })
      continue // a missing file means no block, never a dangling reference
    }
    if (block.type === 'gallery') {
      const items = (block.items || [])
        .map((i) => ({ ...i, image: byLegacyId.get(i.image?.legacyWpId) }))
        .filter((i) => i.image)
      if (items.length) out.push({ ...block, items })
      continue
    }
    out.push(block)
  }
  return out
}

// Client feedback (task 27): ensureCoverInGallery (extract.js) decides
// whether to fold a cover in using the RAW legacy WordPress attachment id,
// before content-based image deduplication (below, in the media import
// loop) has run. Two distinct legacy ids can resolve to the very same Mongo
// Image (a byte-identical file registered twice in WordPress) -- observed on
// the real archive: the cover's own legacy id differed from a gallery item
// that turned out, after resolution, to be the same photo, so
// ensureCoverInGallery correctly saw no match and added a redundant hidden
// reference to an image already visible in the same gallery. Dropped here,
// once every id is a real ObjectId and duplicate identity is unambiguous.
export function dropRedundantHiddenDuplicates(blocks) {
  const visibleIds = new Set()
  for (const b of blocks) {
    if (b.type !== 'gallery') continue
    for (const it of b.items || []) {
      if (!it.hidden && it.image) visibleIds.add(String(it.image))
    }
  }
  if (!visibleIds.size) return blocks
  return blocks.map((b) => {
    if (b.type !== 'gallery') return b
    const items = (b.items || []).filter((it) => !(it.hidden && visibleIds.has(String(it.image))))
    return items.length === (b.items || []).length ? b : { ...b, items }
  })
}

/**
 * Task 30, part 1 (and its part 4 extension, gallery slider mode). Fields
 * the artist owns through the admin, which a load re-run must never
 * clobber: `status`, `cover`, `featured`, each gallery item's `hidden`
 * flag, and each gallery block's own `mode` (grid/slider). Everything else
 * in `fresh` (the update built from the freshly extracted source) is still
 * written every run, so a re-run still picks up corrected content -- this
 * is NOT "skip existing articles wholesale", it is "carry these specific
 * fields forward". `existing` is the current Mongo document (a lean
 * object) or null on first import.
 *
 * Note the direction of each half: extract.js's defaultGalleryMode SETS the
 * migration's own per-category default (every exhibitions gallery starts
 * as 'slider', everything else 'grid'); this function PRESERVES whatever
 * the artist later chose instead, which only matters from the second load
 * onward -- on a first import there is nothing existing to preserve, so the
 * migration's default applies untouched.
 *
 * Gallery item `hidden` is matched by resolved image id, not by position:
 * blocks can be reordered or regenerated by extraction, but an image's own
 * identity survives that, so the artist's hide/show choice for a given photo
 * follows the photo, not a slot. A gallery block's own `mode` has no single
 * image to key off, so it is matched by the block's full set of item image
 * ids instead -- stable across a re-run of the same source content, and a
 * gallery whose membership genuinely changed (no fixture, and therefore no
 * key, in common with anything existing) falls back to the fresh
 * (migration-default) mode, which is the correct behaviour for a gallery
 * that is, from the loader's point of view, new.
 */
function galleryIdentityKey(block) {
  return (block.items || []).map((item) => String(item.image)).sort().join(',')
}

export function preserveArtistFields(existing, fresh) {
  if (!existing) return fresh

  const hiddenByImageId = new Map()
  const modeByGalleryKey = new Map()
  for (const block of existing.blocks || []) {
    if (block.type !== 'gallery') continue
    // Only record a mode the existing document actually HAD. A document
    // loaded before `mode` existed in the schema at all has no such field
    // (not "the artist chose grid" -- "nobody has ever set this"), and must
    // not clobber a fresh migration-set default with undefined -- exactly
    // the live-data incident this guards (see the load.test.js case with
    // the identical name).
    if (block.mode != null) modeByGalleryKey.set(galleryIdentityKey(block), block.mode)
    for (const item of block.items || []) {
      if (item.image != null) hiddenByImageId.set(String(item.image), Boolean(item.hidden))
    }
  }

  const blocks = (fresh.blocks || []).map((block) => {
    if (block.type !== 'gallery') return block
    const key = galleryIdentityKey(block)
    const mode = modeByGalleryKey.has(key) ? modeByGalleryKey.get(key) : block.mode
    return {
      ...block,
      mode,
      items: (block.items || []).map((item) => {
        const imageKey = item.image != null ? String(item.image) : null
        const hidden = imageKey && hiddenByImageId.has(imageKey) ? hiddenByImageId.get(imageKey) : item.hidden
        return { ...item, hidden }
      }),
    }
  })

  return {
    ...fresh,
    status: existing.status,
    cover: existing.cover ?? null,
    featured: existing.featured ?? false,
    blocks,
    // Task 33, section 3: `position` is only ever present on `fresh` for a
    // split exhibition (source-order index among its year's siblings -- see
    // extract.js's splitExhibitionYear); every other category never sets it
    // here at all, and this is a no-op for them (the condition is false, so
    // the spread above is untouched, exactly as before this task). Preserves
    // an artist-chosen reorder (via the admin) the same way status/cover/
    // featured are preserved above: `existing.position` wins whenever it's
    // already set, falling back to the freshly-computed source order only
    // when there is nothing yet to preserve (a genuinely new document).
    ...(fresh.position !== undefined ? { position: existing.position ?? fresh.position } : {}),
  }
}

/**
 * The set of legacy media ids actually used by an article cover, an image
 * block or a gallery item, across both articles and pages. Of the 1282
 * extracted media entries, only ~487 are referenced; the rest are theme SVG
 * icons, WooCommerce placeholders and dead uploads that the artist never
 * chose to publish, and importing them would triple the number of sharp
 * operations for no benefit.
 */
export function collectReferencedIds(articles = [], pages = []) {
  const ids = new Set()
  const addBlocks = (blocks = []) => {
    for (const block of blocks) {
      if (block.type === 'image' && block.image?.legacyWpId) ids.add(block.image.legacyWpId)
      if (block.type === 'gallery') {
        for (const item of block.items || []) {
          if (item.image?.legacyWpId) ids.add(item.image.legacyWpId)
        }
      }
    }
  }
  for (const article of articles) {
    if (article.coverLegacyId) ids.add(article.coverLegacyId)
    addBlocks(article.blocks)
  }
  for (const page of pages) addBlocks(page.blocks)
  return ids
}

// Task 26, part A3. icone-oeuvres.jpg (the old theme's menu-toggle icon) is
// excluded from media.json by extract.js and stripped from every block, so
// a fresh load never imports it. But a Mongo populated by an earlier,
// unfixed run can still hold the Image document and its files from before
// that fix -- this finds any such leftover by filename and, ONLY after
// confirming freshly (against the article/page state this very load run
// just wrote) that nothing references it any more, deletes the document and
// unlinks its variant files, including the `_originals/` master.
const PURGED_ORIGINAL_FILENAMES = new Set(['icone-oeuvres.jpg'])

function collectUsedImageIds(docs) {
  const used = new Set()
  for (const doc of docs) {
    if (doc.cover) used.add(String(doc.cover))
    for (const block of doc.blocks || []) {
      if (block.type === 'image' && block.image) used.add(String(block.image))
      if (block.type === 'gallery') {
        for (const item of block.items || []) {
          if (item.image) used.add(String(item.image))
        }
      }
    }
  }
  return used
}

// Task 33, section 3: splitExhibitionYear (extract.js) leaves a split
// exhibition's slug blank -- extraction has no access to the live Mongo
// state a real uniqueness check needs. Resolved here instead, against the
// database, at load time -- the same pattern the admin API's own
// ensureSlug() already uses (api/src/routes/admin.js): reuses
// api/src/lib/slug.js's uniqueSlug and constants.js's RESERVED_SLUGS
// directly rather than reimplementing either.
//
// `taken` excludes the article's OWN existing document (matched by its own
// stable, synthetic legacyWpId -- see splitExhibitionYear), the same way
// ensureSlug's own `taken` excludes `currentId`: without that, a re-run
// would see its own previously-assigned slug as "already taken" and
// disambiguate against itself every single time, drifting the slug on
// every load rather than keeping it stable.
async function resolveArticleSlug(article) {
  if (article.slug?.fr) return article.slug
  const taken = async (candidate) => {
    if (RESERVED_SLUGS.includes(candidate)) return true
    const hit = await Article.findOne({ 'slug.fr': candidate }).select('legacyWpId').lean()
    return Boolean(hit) && hit.legacyWpId !== article.legacyWpId
  }
  const fr = await uniqueSlug(article.title?.fr || 'exposition', taken)
  return { fr, en: article.slug?.en || '' }
}

// Task 33, section 3: the split changes which documents exist. A pre-split
// year-level exhibitions document (slug "2013", a real WordPress post id)
// has no counterpart in a fresh extraction any more -- splitExhibitionYear
// replaces it with N per-exhibition documents, each at its own synthetic
// (negative) legacyWpId. Left alone, that stale document would keep
// resolving at its old URL with its old, pre-split content forever,
// silently shadowing the new per-exhibition pages (see ArticleDetail.jsx's
// own fallback for those legacy year URLs, which depends on the direct
// fetch genuinely 404ing).
//
// Deliberately scoped to `category: 'exhibitions'` with a POSITIVE
// legacyWpId (a genuine former WP post, never one of the split children,
// whose ids are always negative) -- every other category stays exactly
// 1:1 with its WordPress post, so nothing there can go stale this way
// under ordinary operation, and this must never reach into that case by
// accident.
//
// Not carried forward by preserveArtistFields: there is no single one of
// the N new documents a year-level status/cover/gallery-hidden choice
// could correctly map onto (which exhibition would "inherit" the year's
// own cover?). This is a one-time loss at the migration boundary, not an
// ongoing gap -- see the task report for the full reasoning, and what was
// checked against the real database before this shipped.
export async function pruneStaleExhibitionYears(validLegacyIds) {
  const stale = await Article.find({
    category: 'exhibitions',
    legacyWpId: { $gt: 0, $nin: [...validLegacyIds] },
  }).lean()
  for (const doc of stale) {
    await Article.deleteOne({ _id: doc._id })
  }
  return { pruned: stale.length, ids: stale.map((d) => String(d._id)) }
}

export async function pruneKnownPurgedImages(mediaRoot) {
  const all = await Image.find().lean()
  const candidates = all.filter((img) => PURGED_ORIGINAL_FILENAMES.has((img.legacyUrl || '').split('/').pop()))
  if (!candidates.length) return { pruned: 0, ids: [] }

  const [articles, pages] = await Promise.all([
    Article.find().select('cover blocks').lean(),
    Page.find().select('blocks').lean(),
  ])
  const used = collectUsedImageIds([...articles, ...pages])

  const ids = []
  for (const img of candidates) {
    if (used.has(String(img._id))) continue // still referenced somewhere; leave it alone
    await Promise.all(
      Object.values(img.variants || {})
        .filter(Boolean)
        .map((v) => unlink(join(mediaRoot, v.path)).catch(() => {}))
    )
    await Image.deleteOne({ _id: img._id })
    ids.push(String(img._id))
  }
  return { pruned: ids.length, ids }
}

export async function loadAll({ dataDir, uploadsRoot, mediaRoot, mongoUri, dbName }) {
  await connect(mongoUri, dbName)
  try {
    const read = async (name) => JSON.parse(await readFile(join(dataDir, name), 'utf8'))
    const [articles, pages, media] = await Promise.all([
      read('articles.json'),
      read('pages.json'),
      read('media.json'),
    ])

    const importAll = process.env.MIGRATE_ALL_MEDIA === '1'
    const referenced = collectReferencedIds(articles, pages)

    // A referenced id can fail to resolve for two very different reasons,
    // and they must be reported differently: the id IS in media.json but its
    // file failed to read (skippedMissingFile, below), versus the id is
    // referenced by an article/page but has NO entry in media.json at all.
    // The second case never enters the media loop below, so without this
    // precomputed diff it would resolve to a dropped block / null cover with
    // nothing anywhere saying so - exactly the silent-skip this phase exists
    // to prevent. There are zero such ids in the current dataset, but the
    // migration re-runs at cutover against data that may have changed.
    const mediaIds = new Set(media.map((item) => item.legacyWpId))
    const noMediaEntryIds = [...referenced].filter((id) => !mediaIds.has(id))
    if (noMediaEntryIds.length) {
      console.error(
        `referenced media id(s) with no entry in media.json at all, block/cover will be dropped: ${noMediaEntryIds.join(', ')}`
      )
    }

    const byLegacyId = new Map()
    let imported = 0
    let skippedUnreferenced = 0
    let skippedMissingFile = 0
    let dedupedByContent = 0

    for (const item of media) {
      if (!importAll && !referenced.has(item.legacyWpId)) {
        skippedUnreferenced += 1
        continue
      }
      const existing = await Image.findOne({ legacyWpId: item.legacyWpId })
      if (existing) {
        byLegacyId.set(item.legacyWpId, existing._id)
        imported += 1
        continue
      }
      let buffer
      try {
        buffer = await readFile(join(uploadsRoot, item.file))
      } catch {
        console.warn(`missing upload, skipped: ${item.file}`)
        skippedMissingFile += 1
        continue
      }
      const fields = await processImage(buffer, { originalName: item.originalName, mediaRoot })
      // WordPress sometimes registers the same physical upload under two
      // distinct attachment ids (e.g. a post duplicated the media library
      // entry rather than the file). `Image.filename` is a content hash and
      // carries a unique index, so a second legacyWpId with byte-identical
      // content must reuse that existing document rather than attempt a
      // second insert, which would throw E11000 on `filename_1`.
      const byContent = await Image.findOne({ filename: fields.filename })
      if (byContent) {
        byLegacyId.set(item.legacyWpId, byContent._id)
        imported += 1
        dedupedByContent += 1
        continue
      }
      const doc = await Image.findOneAndUpdate(
        { legacyWpId: item.legacyWpId },
        { ...fields, legacyWpId: item.legacyWpId, legacyUrl: `/wp-content/uploads/${item.file}` },
        { upsert: true, new: true, setDefaultsOnInsert: true }
      )
      byLegacyId.set(item.legacyWpId, doc._id)
      imported += 1
    }
    console.log(
      `media: imported ${imported} (${dedupedByContent} deduped by content), skipped as unreferenced ${skippedUnreferenced}, skipped (file missing) ${skippedMissingFile}, skipped (no media.json entry) ${noMediaEntryIds.length}`
    )

    for (const article of articles) {
      // Task 30, part 1: read the existing document first so
      // preserveArtistFields can carry the artist's own edits forward. The
      // point of a re-run is still to pick up corrected source content, so
      // every other field below is always rebuilt fresh, never skipped.
      const existing = await Article.findOne({ legacyWpId: article.legacyWpId }).lean()
      const fresh = {
        category: article.category,
        status: article.status,
        slug: await resolveArticleSlug(article),
        title: article.title,
        yearLabel: article.yearLabel,
        yearStart: article.yearStart,
        yearEnd: article.yearEnd,
        subtitle: article.subtitle || { fr: '', en: '' },
        cover: byLegacyId.get(article.coverLegacyId) || null,
        featured: false,
        blocks: dropRedundantHiddenDuplicates(resolveBlockImages(article.blocks, byLegacyId)),
        legacyWpId: article.legacyWpId,
        // Task 33, section 3: only a split exhibition carries its own
        // `position` out of extract.js (source-order index among its
        // year's siblings) -- every other category's position is left
        // untouched here, exactly as before this task (see
        // preserveArtistFields' own comment for what that means on a
        // re-run).
        ...(article.category === 'exhibitions' ? { position: article.position ?? 0 } : {}),
      }
      await Article.findOneAndUpdate(
        { legacyWpId: article.legacyWpId },
        preserveArtistFields(existing, fresh),
        { upsert: true, new: true, setDefaultsOnInsert: true, runValidators: true }
      )
    }

    // Task 33, section 3: removes any pre-split exhibitions year document
    // (a positive legacyWpId) the fresh extraction no longer accounts for
    // -- see pruneStaleExhibitionYears' own comment for the full reasoning.
    const { pruned: exhibitionYearsPruned } = await pruneStaleExhibitionYears(articles.map((a) => a.legacyWpId))
    if (exhibitionYearsPruned) {
      console.log(`pruned ${exhibitionYearsPruned} stale pre-split exhibitions year document(s)`)
    }

    let pageCount = 0
    const unmappedPageSlugs = []
    for (const page of pages) {
      const key = PAGE_KEY_BY_SLUG[page.sourceSlug]
      if (!key || !PAGE_KEYS.includes(key)) {
        console.warn(`unmapped page slug, skipped: ${page.sourceSlug}`)
        unmappedPageSlugs.push(page.sourceSlug)
        continue
      }
      await Page.findOneAndUpdate(
        { key },
        { key, title: page.title, blocks: resolveBlockImages(page.blocks, byLegacyId) },
        { upsert: true, new: true, setDefaultsOnInsert: true, runValidators: true }
      )
      pageCount += 1
    }

    const { pruned: imagesPruned } = await pruneKnownPurgedImages(mediaRoot)
    if (imagesPruned) console.log(`pruned ${imagesPruned} leftover legacy image(s) no longer referenced`)

    return {
      images: imported,
      imagesDedupedByContent: dedupedByContent,
      imagesSkippedUnreferenced: skippedUnreferenced,
      imagesSkippedMissingFile: skippedMissingFile,
      imagesPruned,
      unresolvedRefs: { count: noMediaEntryIds.length, ids: noMediaEntryIds },
      articles: articles.length,
      exhibitionYearsPruned,
      pages: pageCount,
      unmappedPageSlugs,
    }
  } finally {
    await disconnect()
  }
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const started = Date.now()
  loadAll({
    dataDir: new URL('./data/', import.meta.url).pathname,
    uploadsRoot: process.env.UPLOADS_ROOT || new URL('./uploads/', import.meta.url).pathname,
    mediaRoot: process.env.MEDIA_ROOT || '/tmp/philippe-media',
    mongoUri: process.env.MONGO_URI,
    dbName: process.env.MONGO_DB,
  }).then((counts) => {
    const elapsedSec = ((Date.now() - started) / 1000).toFixed(1)
    console.log('loaded', counts, `in ${elapsedSec}s`)
  })
}
